sudo: false
branches:
    only:
        - master
        - stable
language: python
python:
    - '2.7'
cache: apt
addons:
  apt:
    packages:
      - libatlas-dev
      - libatlas-base-dev
      - liblapack-dev
      - gfortran
      - python-numpy
      - python-scipy
install:
    - pip install -r requirements.txt
    - pip install --upgrade --force-reinstall pytest>=3
script:
    - python -m pytest -v --color=yes
os:
  - linux